### ISSUE TITLE
ImageManager: Jigsaw pieces don't stretch to fit a non-square puzzle

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#10]
Jigsaw pieces shouldn't stretch to fit a non-square puzzle. Instead, all puzzles should have the same uniform square pieces and choose a scale/puzzleDimensions which divide into uniform pieces. 

Not a high priority for first release; I can just always use only square images for puzzles for now.

**Comment by ByteSheep** [comment]
I guess the commit I pushed is actually more relevant to issue #4... Not sure if this is what you had in mind, but it should be a good starting point - I might need more clarification on this particular issue though :)
The Scale method added could be used for solving issue #8 as well.

**Comment by TimChroma** [comment]
Yeah, it all seems pretty connected. Large images looking way better. I think I can play with some values to define a max board size so there is still plenty of space for loose pieces. 

Some more detail for this issue though; when choosing difficulty we set these values per difficulty: 

	public void PlayPuzzle(int puzzleIndex, PuzzleDifficulty difficulty) {

		switch (difficulty)
		{
		case PuzzleDifficulty.EASY:
			puzzleBoard.piecesX = 2;
			puzzleBoard.piecesY = 2;
			break;
		case PuzzleDifficulty.MEDIUM:
			puzzleBoard.piecesX = 3;
			puzzleBoard.piecesY = 3;
			break;
		case PuzzleDifficulty.HARD:
			puzzleBoard.piecesX = 4;
			puzzleBoard.piecesY = 4;
			break;
		}

It would be ideal if we can define the X and Y pieces based on the image dimensions, so the resulting pieces are always square, instead of stretched to fit. So for example, if an image is landscape, we have something more like:

pieceSize = fixed dimensions, like 100 pixels X 100 pixels
		case PuzzleDifficulty.EASY:
   			puzzleBoard.piecesX = imageWidth/pieceSize;
			puzzleBoard.piecesY = imageHeight/pieceSize;
			break;

I guess there may be some issue with handling scaling when an image doesn't have X and Y dimensions which divide evenly into uniform sections. Open to suggestions! Puzzle World on Facebook does a good job of solving this problem for reference FYI.

**Comment by TimChroma** [comment]
Some practical examples; the peacock looks great, as it is originally square, so all pieces are evenly sized. 

The lion cub and big cat images are not square, so they are both 

a) squished in the puzzle menus
b) have non-uniform pieces when they are loaded, as the puzzleDifficulty.<DIFFICULTY> isn't dynamic

Hope that makes the problems I want to solve clearer

**Comment by TimChroma** [comment]
OK wow, you fixed it already :D I missed the commit. Awesome! Looks great! What solution did you use? Making all the images squares? That totally works for me

**Comment by ByteSheep** [comment]
Non-square images should now be supported :)
Basically, instead of turning each image into a square (for example a 600x400 image would become 400x400) we try to find the nearest divisible dimensions. If we set our target piece count to 3 then our puzzle piece size would be 200x200 and our image would remain scaled at 600x400, with width divided by 3 and height by 2.
If we set the piece count to 4 the image would be cropped to 600x300 with width divided by 4 and height by 2 (puzzle piece size would be 150x150).
So of course the more pieces that are used, the less likely it is that a big part of the image will have to be cropped..
Hope that made sense, in practice it's still good to try to use fairly squarish images so that puzzles with few pieces will look good :D
